default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mizocafe_development

test:
  <<: *default
  database: mizocafe_test

production:
  <<: *default
  database: mizocafe_production
  username: mizocafe
  password: <%= ENV['MIZOCAFE_DATABASE_PASSWORD'] %>
